#!/bin/bash
# Double-click this file in Finder (or run it in a terminal) to set up Trailhead.
#
# It will:
#   1. Ask which LLM provider you want and configure core.py for it.
#   2. Prompt for that provider's API key and write the .env file.
#   3. Create the Python environment and install packages (or reinstall it).

# Move into the folder this script lives in, regardless of where it's run from.
cd "$(dirname "$0")" || exit 1

# Stop on the first unhandled error so a half-finished setup is obvious.
set -e

CORE="core.py"
ENV_FILE=".env"

# The virtual environment lives OUTSIDE this folder, in ~/.venvs, on purpose:
# this project sits in ~/Documents, which iCloud Drive syncs, and iCloud cannot
# keep up with the thousands of tiny files in a Python environment. Keeping the
# venv in a non-synced location avoids silent "No module named ..." crashes.
# This path must match the one in run.command.
VENV_DIR="$HOME/.venvs/trailhead"

echo "=== Trailhead installer ==="
echo

# ---------------------------------------------------------------------------
# 1. Choose the LLM provider and write it into core.py.
# ---------------------------------------------------------------------------
# Read the provider currently set in core.py so we can offer to keep it (handy
# when you just want to rebuild the venv without touching your config/key).
CURRENT_PROVIDER=$(sed -n -E 's|^LLM_PROVIDER[[:space:]]*=[[:space:]]*"([^"]*)".*|\1|p' "$CORE")
[ -z "$CURRENT_PROVIDER" ] && CURRENT_PROVIDER="unknown"

echo "Which LLM provider do you want to use?"
echo "  1) OpenAI   (api.openai.com)"
echo "  2) TAMU AI  (chat-api.tamu.ai)"
echo "  3) None     (no LLM — you write summaries yourself, no key needed)"
echo "  4) Leave unchanged (currently \"$CURRENT_PROVIDER\"; keep core.py and .env as-is)"
PROVIDER=""
while [ -z "$PROVIDER" ]; do
    printf "Enter 1, 2, 3, or 4: "
    read -r choice
    case "$choice" in
        1) PROVIDER="openai" ;;
        2) PROVIDER="tamu" ;;
        3) PROVIDER="none" ;;
        4) PROVIDER="keep" ;;
        *) echo "Please type 1, 2, 3, or 4." ;;
    esac
done

if [ "$PROVIDER" = "keep" ]; then
    # Don't touch core.py or .env — go straight to the environment step.
    echo "Leaving LLM provider as \"$CURRENT_PROVIDER\" and keeping the existing .env."
    echo
else
    # Match the provider to the env-var name core.py expects for its key.
    # "none" needs no key.
    case "$PROVIDER" in
        openai) KEY_VAR="OPENAI_API_KEY" ;;
        tamu)   KEY_VAR="TAMU_AI_API_KEY" ;;
        none)   KEY_VAR="" ;;
    esac

    # Replace the LLM_PROVIDER line in core.py. The pattern matches any current
    # value so re-running the installer flips the provider cleanly.
    if ! grep -Eq '^LLM_PROVIDER[[:space:]]*=' "$CORE"; then
        echo "Error: could not find an 'LLM_PROVIDER =' line in $CORE." >&2
        exit 1
    fi
    sed -i '' -E "s|^LLM_PROVIDER[[:space:]]*=.*|LLM_PROVIDER = \"$PROVIDER\"|" "$CORE"
    echo "Set LLM_PROVIDER = \"$PROVIDER\" in $CORE."
    echo

    # -----------------------------------------------------------------------
    # 2. Prompt for the API key and write the .env file.
    # -----------------------------------------------------------------------
    if [ "$PROVIDER" = "none" ]; then
    # No LLM means no key — write a placeholder .env so nothing downstream trips
    # over a missing file.
    {
        echo "# Generated by install.command for provider: none"
        echo "# No LLM provider selected, so no API key is needed."
    } > "$ENV_FILE"
    echo "Provider is 'none' — no API key needed. Wrote a placeholder $ENV_FILE."
else
    esc=$(printf '\033')
    API_KEY=""
    while [ -z "$API_KEY" ]; do
        printf "Paste your %s key, then press Enter: " "$KEY_VAR"
        # Turn off the terminal's "bracketed paste" mode before reading. With
        # it on (the default in modern terminals) a paste arrives wrapped in
        # invisible escape codes — ESC[200~ ... ESC[201~ — which get stored as
        # part of the key and silently corrupt it, so the app later rejects a
        # key that looked right. Disabling it delivers the pasted text as-is.
        printf '\033[?2004l'
        # -s hides the key as it's pasted.
        read -rs API_KEY
        echo
        # Belt and suspenders: on any terminal that ignored the disable above,
        # strip leftover bracketed-paste markers, then all whitespace (API keys
        # never contain spaces, so trimming every space/newline is safe).
        API_KEY=$(printf '%s' "$API_KEY" \
            | sed "s/${esc}\[20[01]~//g" \
            | tr -d '[:space:]')
        if [ -z "$API_KEY" ]; then
            echo "The key can't be empty."
        fi
    done
    echo "Got your $KEY_VAR (${#API_KEY} characters)."

    # Write a fresh .env containing just the active provider's key.
    {
        echo "# Generated by install.command for provider: $PROVIDER"
        echo "$KEY_VAR=$API_KEY"
    } > "$ENV_FILE"
    echo "Wrote $ENV_FILE with $KEY_VAR."
    fi
    echo
fi

# ---------------------------------------------------------------------------
# 3. Create or reinstall the Python environment.
# ---------------------------------------------------------------------------
INSTALL=true
if [ -d "$VENV_DIR" ]; then
    echo "A Python environment already exists at:"
    echo "  $VENV_DIR"
    printf "Reinstall it from scratch? [y/N]: "
    read -r ans
    case "$ans" in
        [Yy]*)
            echo "Removing the existing environment..."
            rm -rf "$VENV_DIR"
            ;;
        *)
            echo "Keeping the existing environment."
            INSTALL=false
            ;;
    esac
fi

if [ "$INSTALL" = true ]; then
    echo "Creating Python environment at $VENV_DIR ..."
    python3 -m venv "$VENV_DIR"
    # shellcheck disable=SC1091
    source "$VENV_DIR/bin/activate"
    echo "Installing packages (this can take a few minutes)..."
    pip install --upgrade pip
    pip install -r requirements.txt
    echo "Packages installed."
fi

echo
echo "=== Setup complete. ==="
echo "Launch the app by double-clicking run.command (or running ./run.command)."
